'From Cuis7.1 [latest update: #6858] on 30 November 2024 at 8:42:19 pm'!
'Description '!
!provides: 'Neo-CSV-Examples' 1 1!
SystemOrganization addCategory: #'Neo-CSV-Examples'!


!classDefinition: #ListOfCapitals category: #'Neo-CSV-Examples'!
Object subclass: #ListOfCapitals
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Neo-CSV-Examples'!
!classDefinition: 'ListOfCapitals class' category: #'Neo-CSV-Examples'!
ListOfCapitals class
	instanceVariableNames: ''!

!classDefinition: #ReadCapitals category: #'Neo-CSV-Examples'!
Object subclass: #ReadCapitals
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Neo-CSV-Examples'!
!classDefinition: 'ReadCapitals class' category: #'Neo-CSV-Examples'!
ReadCapitals class
	instanceVariableNames: ''!


!ListOfCapitals class methodsFor: 'accessing' stamp: 'hjh 11/30/2024 20:36:39'!
csvString

"Source: https://en.wikipedia.org/wiki/List_of_national_capitals
accessed 30-Nov-2024
copied into notepad, then into LibreOffice Writer and converted table to comma separated value list; minor edits; omitted comment column"

^'Abidjan (former capital), Ivory Coast (Côte d''Ivoire),Africa
Abu Dhabi, United Arab Emirates,Asia
Abuja, Nigeria,Africa
Accra, Ghana,Africa
Adamstown, Pitcairn Islands,Oceania
Addis Ababa, Ethiopia,Africa
Aden (de facto temporary), Yemen,Asia
Algiers, Algeria,Africa
Alofi, Niue,Oceania
Amman, Jordan,Asia
Amsterdam (official), Netherlands,Europe
Andorra la Vella, Andorra,Europe
Ankara, Turkey,Asia
Antananarivo, Madagascar,Africa
Apia, Samoa,Oceania
Ashgabat, Turkmenistan,Asia
Asmara, Eritrea,Africa
Astana, Kazakhstan,Asia
Asunción, Paraguay,South America
Athens, Greece,Europe
Avarua, Cook Islands,Oceania
Baghdad, Iraq,Asia
Baku, Azerbaijan,Asia
Bamako, Mali,Africa
Bandar Seri Begawan, Brunei,Asia
Bangkok, Thailand,Asia
Bangui, Central African Republic,Africa
Banjul, Gambia,Africa
Basseterre, Saint Kitts and Nevis,North America
Beijing, China,Asia
Beirut, Lebanon,Asia
Belgrade, Serbia,Europe
Belmopan, Belize,North America
Berlin, Germany,Europe
Bern (de facto), Switzerland,Europe
Bishkek, Kyrgyzstan,Asia
Bissau, Guinea-Bissau,Africa
Bloemfontein (judicial), South Africa,Africa
Bogotá, Colombia,South America
Brades (de facto), Montserrat,North America
Brasília, Brazil,South America
Bratislava, Slovakia,Europe
Brazzaville, Congo,Africa
Bridgetown, Barbados,North America
Brussels, Belgium,Europe
Brussels, European Union (de facto),Europe
Bucharest, Romania,Europe
Budapest, Hungary,Europe
Buenos Aires, Argentina,South America
Bujumbura (de facto), Burundi,Africa
Cairo, Egypt,Africa
Canberra, Australia,Oceania
Cape Town (legislative), South Africa,Africa
Caracas, Venezuela,South America
Castries, Saint Lucia,North America
Charlotte Amalie, United States Virgin Islands,North America
Chișinău, Moldova,Europe
Cockburn Town, Turks and Caicos Islands,North America
Colombo, Sri Lanka,Asia
Comayagüela, Honduras,North America
Conakry, Guinea,Africa
Copenhagen, Denmark,Europe
Cotonou (de facto), Benin,Africa
Dakar, Senegal,Africa
Damascus, Syria,Asia
Dhaka, Bangladesh,Asia
Diego Garcia (de facto), British Indian Ocean Territory,Asia
Dili, East Timor,Asia
Djibouti, Djibouti,Africa
Dodoma, Tanzania,Africa
Doha, Qatar,Asia
Douglas, Isle of Man,Europe
Dublin, Ireland,Europe
Dushanbe, Tajikistan,Asia
Edinburgh of the Seven Seas, Tristan da Cunha,
Episkopi Cantonment, Akrotiri and Dhekelia,Asia
Europe,Brussels,Europe
Flying Fish Cove, Christmas Island,
Freetown, Sierra Leone,Africa
Funafuti, Tuvalu,Oceania
Gaborone, Botswana,Africa
George Town, Cayman Islands,North America
Georgetown, Ascension Island,
Georgetown, Guyana,South America
Gibraltar, Gibraltar,Europe
Gitega (de jure), Burundi,Africa
Guatemala City, Guatemala,North America
Gustavia, Saint Barthélemy,North America
Hagåtña, Guam,Oceania
Hamilton, Bermuda,North America
Hanoi, Vietnam,Asia
Harare, Zimbabwe,Africa
Hargeisa, Somaliland,Africa
Havana, Cuba,North America
Helsinki, Finland,Europe
Honiara, Solomon Islands,Oceania
Islamabad, Pakistan,Asia
Jakarta, Indonesia,Asia
Jamestown, Saint Helena,
Jerusalem, Israel,Asia
Jerusalem, Palestine,
Juba, South Sudan,Africa
Kabul, Afghanistan,Asia
Kampala, Uganda,Africa
Kathmandu, Nepal,Asia
Khartoum, Sudan,Africa
Kigali, Rwanda,Africa
King Edward Point, South Georgia and the South Sandwich Islands,
Kingston, Jamaica,North America
Kingston, Norfolk Island,Oceania
Kingstown, Saint Vincent and the Grenadines,North America
Kinshasa, Democratic Republic of the Congo,Africa
Kuala Lumpur, Malaysia,Asia
Kuwait City, Kuwait,Asia
Kyiv, Ukraine,Europe
La Paz (administrative), Bolivia,South America
Laayoune (declared), Western Sahara,Africa
Libreville, Gabon,Africa
Lilongwe, Malawi,Africa
Lima, Peru,South America
Lisbon, Portugal,Europe
Ljubljana, Slovenia,Europe
Lobamba (royal and legislative), Eswatini,Africa
Lomé, Togo,Africa
London, United Kingdom,Europe
London (administration), British Indian Ocean Territory,Asia
Luanda, Angola,Africa
Lusaka, Zambia,Africa
Luxembourg, Luxembourg,Europe
Madrid, Spain,Europe
Majuro, Marshall Islands,Oceania
Malabo, Equatorial Guinea,Africa
Malé, Maldives,Asia
Managua, Nicaragua,North America
Manama, Bahrain,Asia
Manila, Philippines,Asia
Maputo, Mozambique,Africa
Mariehamn, Åland Islands,Europe
Marigot, Saint Martin,North America
Maseru, Lesotho,Africa
Mata Utu, Wallis and Futuna,Oceania
Mbabane (administrative), Eswatini,Africa
Mexico City, Mexico,North America
Minsk, Belarus,Europe
Mogadishu, Somalia,Africa
Monaco, Monaco,Europe
Monrovia, Liberia,Africa
Montevideo, Uruguay,South America
Moroni, Comoros,Africa
Moscow, Russia,Europe
Muscat, Oman,Asia
N''Djamena, Chad,Africa
Nairobi, Kenya,Africa
Nassau, Bahamas The,North America
Naypyidaw, Myanmar,Asia
New Delhi, India,Asia
Ngerulmud, Palau,Oceania
Niamey, Niger,Africa
Nicosia, Cyprus,Asia
Nicosia, Northern Cyprus,Asia
Nouakchott, Mauritania,Africa
Nouméa, New Caledonia,Oceania
Nukuʻalofa, Tonga,Oceania
Nuuk, Greenland,North America
Oranjestad, Aruba,South America
Oslo, Norway,Europe
Ottawa, Canada,North America
Ouagadougou, Burkina Faso,Africa
Pago Pago, American Samoa,Oceania
Palikir, Micronesia,Oceania
Panama City, Panama,North America
Papeete, French Polynesia,Oceania
Paramaribo, Suriname,South America
Paris, France,Europe
Philipsburg, Sint Maarten,North America
Phnom Penh, Cambodia,Asia
Plymouth (de jure), Montserrat,North America
Podgorica, Montenegro,Europe
Port Louis, Mauritius,Africa
Port Moresby, Papua New Guinea,Oceania
Port of Spain, Trinidad and Tobago,South America
Port Vila, Vanuatu,Oceania
Port-au-Prince, Haiti,North America
Porto-Novo (official), Benin,Africa
Prague, Czech Republic,Europe
Praia, Cape Verde,Africa
Pretoria (executive), South Africa,Africa
Pristina, Kosovo,Europe
Putrajaya, Malaysia,Asia
Pyongyang, North Korea,Asia
Quito, Ecuador,South America
Rabat, Morocco,Africa
Ramallah (de facto), Palestine,Asia
Reykjavík, Iceland,Europe
Riga, Latvia,Europe
Riyadh, Saudi Arabia,Asia
Road Town, British Virgin Islands,North America
Rome, Italy,Europe
Roseau, Dominica,North America
Rothera, British Antarctic Territory,Antarctica
Saint-Pierre (administration), French Southern and Antarctic Lands,
Saipan, Northern Mariana Islands,Oceania
San José, Costa Rica,North America
San Juan, Puerto Rico,North America
San Marino, San Marino,Europe
San Salvador, El Salvador,North America
Sanaa (de jure), Yemen,Asia
Santiago, Chile,South America
Santo Domingo, Dominican Republic,North America
São Tomé, São Tomé and Príncipe,Africa
Sarajevo, Bosnia and Herzegovina,Europe
Seoul, South Korea,Asia
Singapore, Singapore,Asia
Skopje, North Macedonia,Europe
Sofia, Bulgaria,Europe
South Tarawa, Kiribati,Oceania
Sri Jayawardenepura Kotte (official), Sri Lanka,Asia
St. George''s, Grenada,North America
St. Helier, Jersey,Europe
St. John''s, Antigua and Barbuda,North America
St. Peter Port, Guernsey,Europe
St. Pierre, Saint Pierre and Miquelon,North America
Stanley, Falkland Islands,South America
Stockholm, Sweden,Europe
Sucre (constitutional), Bolivia,South America
Sukhumi, Abkhazia,Asia/Europe
Suva, Fiji,Oceania
Taipei, Taiwan,Asia
Tallinn, Estonia,Europe
Tashkent, Uzbekistan,Asia
Tbilisi, Georgia,Asia/Europe
Tegucigalpa, Honduras,North America
Tehran, Iran,Asia
The Hague (de facto), Netherlands,Europe
The Valley, Anguilla,North America
Thimphu, Bhutan,Asia
Tifariti (de facto), Western Sahara,Africa
Tirana, Albania,Europe
Tiraspol, Transnistria,Europe
Tokyo, Japan,Asia
Tórshavn, Faroe Islands,Europe
Tripoli, Libya,Africa
Tskhinvali, South Ossetia,Asia/Europe
Tunis, Tunisia,Africa
Ulaanbaatar, Mongolia,Asia
Vaduz, Liechtenstein,Europe
Valletta, Malta,Europe
Vatican City, Vatican City,Europe
Victoria, Seychelles,Africa
Vienna, Austria,Europe
Vientiane, Laos,Asia
Vilnius, Lithuania,Europe
Warsaw, Poland,Europe
Washington D.C., United States,North America
Wellington, New Zealand,Oceania
West Island, Cocos (Keeling) Islands,
Willemstad, Curaçao,
Windhoek, Namibia,Africa
Yamoussoukro (de jure), Ivory Coast (Côte d''Ivoire),Africa
Yaoundé, Cameroon,Africa
Yaren (de facto), Nauru,Oceania
Yerevan, Armenia,Asia
Zagreb, Croatia,Europe'
! !

!ReadCapitals class methodsFor: 'as yet unclassified' stamp: 'hjh 11/30/2024 20:36:06'!
do
"
self do explore
"

 ^(NeoCSVReader on: ListOfCapitals csvString readStream) upToEnd ! !
